UK_house_price_stats_source: http://publicdata.landregistry.gov.uk/market-trend-data/house-price-index-data/UK-HPI-full-file-YEAR-MONTH.csv
UK_geojson_source: https://open-geography-portalx-ons.hub.arcgis.com/api/download/v1/items/729ef47ece1d486c883248d71bc3921f/geojson?layers=0
UK_geojson_filename: LAD_MAY_2025_UK_BUC_-659679952066429304.geojson
UK_geojson_highres_filename: LAD_MAY_2025_UK_BGC_V2_-5651545108417053320.geojson
UK_cpi_source: https://www.ons.gov.uk/economy/inflationandpriceindices/datasets/consumerpriceindices/current/
UK_cpi_filename: mm23.csv